# IF YOU MODIFY THIS FILE to add or remove "make" targets,
# please also modify the travis: target in the Makefile.
# They're not automatically coordinated, the reason being that
# we want to split the Travis build into multiple jobs.

dist: trusty
sudo: required
language: ocaml
cache:
  apt: true
  directories:
  - $HOME/.opam
  - build/compcert
  - build/sepcomp
  - build/msl
  - build/veric
  - build/floyd
  - build_beta/compcert
  - build_beta/sepcomp
  - build_beta/msl
  - build_beta/veric
  - build_beta/floyd
addons:
  apt:
    sources:
    - avsm
    packages:
    - opam
    - aspcud
env:
  global:
  - NJOBS=2
  # system is == 4.02.3
#  - COMPILER="4.02.3+32bit"
  - COMPILER="default"
  - COQ_VERSION="8.9.0"
  - NEXT_VERSION="8.9.0"

branches:
  only:
  - master
notifications:
  email:
    recipients:
    - vst-push@lists.cs.princeton.edu
git:
  depth: 3

install:
- opam --version
- "[ -e .opam ] || opam init -j ${NJOBS} -n -y"
- opam switch list
- opam switch ${COMPILER}
- eval $(opam config env)
- opam config list
- opam config var root
- opam repo add coq-core-dev https://coq.inria.fr/opam/core-dev || true
- opam update
- opam show coq
- opam install -j ${NJOBS} -y coq=${COQ_VERSION} ${EXTRA_OPAM}
- opam list
- file `which coqc`

stages:
  - setup
  - test

script: echo "No script"

jobs:
 include:
  - stage: setup
    name: "Floyd 32-bit"
    script: ./.travis-script floyd
    env: BITSIZE=32
  - stage: setup
    name: "Floyd 64-bit"
    script: ./.travis-script floyd
    env: BITSIZE=64
  - stage: test
    name: "Progs 32-bit"
    script: ./.travis-script progs
    env: BITSIZE=32
  - stage: test
    name: "Progs 64-bit"
    script: ./.travis-script progs64
    env: BITSIZE=64
  - stage: test
    name: "SHA-HMAC 32-bit"
    script: ./.travis-script sha-hmac
    env: BITSIZE=32
  - stage: test
    name: "Mailbox 32-bit"
    script: ./.travis-script mailbox
    env: BITSIZE=32
#    script:
#    - echo 'Building VST (Coq beta)...' && echo -en 'travis_fold:start:VST.build_beta\\r'
#    - opam switch create coq_beta ocaml-base-compiler.4.07.1 || true
#    - opam switch coq_beta
#    - eval $(opam config env)
#    - opam repo add coq-core-dev https://coq.inria.fr/opam/core-dev || true
#    - opam update
#    - opam install -j ${NJOBS} -y coq=${NEXT_VERSION} ${EXTRA_OPAM}
#    - git show --format='COMMIT %H %ci' -s; coqc -v
#    - mkdir -p build_beta
#    - for i in `ls -a | grep -Ev '^(build_beta|\.\.?)$'`; do rsync -rc $i build_beta; done
#    - cd build_beta; make -j ${NJOBS} TIMINGS=simple IGNORECOQVERSION=true floyd calibrate
#    - echo -en 'travis_fold:end:VST.build_beta\\r'
#    env: BITSIZE=32
  