# IF YOU MODIFY THIS FILE to add or remove "make" targets,
# please also modify the travis: target in the Makefile.
# They're not automatically coordinated, the reason being that
# we want to split the Travis build into multiple jobs.

dist: trusty
sudo: required
language: ocaml
cache:
  apt: true
  directories:
  - $HOME/.opam
  - build/compcert
  - build/sepcomp
  - build/msl
  - build/veric
  - build/floyd
addons:
  apt:
    sources:
    - avsm
    packages:
    - opam
    - aspcud
env:
  global:
  - NJOBS=4
  # system is == 4.02.3
  - COMPILER="4.02.3+32bit"
  - COQ_VERSION="8.7.0"
branches:
  only:
  - master
  - fix_bug_tc_environ
notifications:
  email:
    recipients:
    - vst-push@lists.cs.princeton.edu
git:
  depth: 3

install:
- "[ -e .opam ] || opam init -j ${NJOBS} --compiler=${COMPILER} -n -y"
- eval $(opam config env)
- opam config list
- opam config var root
- opam install -j ${NJOBS} -y coq=${COQ_VERSION} ${EXTRA_OPAM}
- opam list
- file `which coqc`

jobs:
  include:
  - stage: setup
    script:
    - echo 'Building VST...' && echo -en 'travis_fold:start:VST.build\\r'
    - mkdir -p build
    - for i in `ls -a | grep -Ev '^(build|\.\.?)$'`; do rsync -rc $i build; done
    - cd build; make -j ${NJOBS} IGNORECOQVERSION=true floyd
    - echo -en 'travis_fold:end:VST.build\\r'
  - stage: test
    script:
    - echo 'Building progs...' && echo -en 'travis_fold:start:progs.build\\r'
    - mkdir -p build
    - for i in `ls -a | grep -Ev '^(build|\.\.?)$'`; do rsync -rc $i build; done
    - cd build; make -j ${NJOBS} IGNORECOQVERSION=true progs
    - echo -en 'travis_fold:end:progs.build\\r'
  - script:
    - echo 'Building hmacdrbg...' && echo -en 'travis_fold:start:hmacdrbg.build\\r'
    - mkdir -p build
    - for i in `ls -a | grep -Ev '^(build|\.\.?)$'`; do rsync -rc $i build; done
    - cd build; make -j ${NJOBS} IGNORECOQVERSION=true hmacdrbg
    - echo -en 'travis_fold:end:hmacdrbg.build\\r'
  - script:
    - echo 'Building mailbox...' && echo -en 'travis_fold:start:mailbox.build\\r'
    - mkdir -p build
    - for i in `ls -a | grep -Ev '^(build|\.\.?)$'`; do rsync -rc $i build; done
    - cd build; travis_wait make -j ${NJOBS} IGNORECOQVERSION=true mailbox
    - echo -en 'travis_fold:end:mailbox.build\\r'
#  - script:
#    - echo 'Building atomics...' && echo -en 'travis_fold:start:atomics.build\\r'
#    - mkdir -p build
#    - for i in `ls -a | grep -Ev '^(build|\.\.?)$'`; do rsync -rc $i build; done
#    - cd build; travis_wait 50 make -j ${NJOBS} IGNORECOQVERSION=true atomics
#    - echo -en 'travis_fold:end:atomics.build\\r'
