---
name: CI

on:
  push:
    branches:
      - master
      - release-v2.7
      - release-v2.8
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        coq_version:
          # See https://github.com/coq-community/docker-coq/wiki for supported images
          - '8.13'
          - '8.14'
        opam_name:
          - coq-vst
          - coq-vst-32
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: coq-community/docker-coq-action@v1
        with:
          opam_file: ${{ matrix.opam_name }}.opam
          coq_version: ${{ matrix.coq_version }}
          # See https://github.com/coq-community/docker-coq-action/tree/v1 for usage
          before_install: |
              startGroup "Opam config"
                opam repo add -y prerelease file://$WORKDIR/opam-prerelease
                opam config list; opam repo list; opam list
              endGroup
          export: 'OPAMWITHTEST'
        env:
          OPAMWITHTEST: 'true'
